cp example-time-series.pdf $1/figure01.pdf
cp noise-map-adjusted.pdf  $1/figure02.pdf
cp distance-to-threshold-scatter.pdf $1/figure03.pdf
cp distance-vs-dnoise.pdf $1/figure04.pdf
cp autocor-by-dnoise.pdf $1/figure05.pdf
cp autocor-by-dnoise-20yr.pdf $1/figure06.pdf
cp distance-vs-fnoise.pdf $1/figure07.pdf
cp distance-vs-popsize.pdf $1/figure08.pdf
cp distance-vs-sampling-freq.pdf $1/figure09.pdf
cp change-in-distance.pdf $1/figure10.pdf
cp distance-vs-reporting-prob.pdf $1/figure11.pdf
