cp example-time-series.pdf $1/figure01.pdf
cp noise-map-adjusted.pdf  $1/figure02.pdf
cp distance-to-threshold-scatter.pdf $1/figure03.pdf
cp distance-vs-dnoise.pdf $1/figureS2.pdf
cp autocor-by-dnoise.pdf $1/figureS3.pdf
cp autocor-by-dnoise-20yr.pdf $1/figureS4.pdf
cp distance-vs-fnoise.pdf $1/figureS5.pdf
cp distance-vs-popsize.pdf $1/figureS1.pdf
cp distance-vs-sampling-freq.pdf $1/figure04.pdf
cp change-in-distance.pdf $1/figureS6.pdf
cp distance-vs-reporting-prob.pdf $1/figure05.pdf
